apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: example-container
        image: intro-to-docker-and-kubernetes:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000  # Ensure the container port matches the application's port
