apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  type: NodePort
  selector:
    app: example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # Ensure the target port matches the application's port
      nodePort: 30001  # NodePort should be within the range 30000-32767
